services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reactions-webapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/reactions-webapp
      - ./migrations:/reactions-webapp/migrations:rw
    command: >
      uvicorn reactions.interfaces.routes:app
      --host=0.0.0.0
      --port=8000
      --reload
    depends_on:
      - postgres
    networks:
      - reactions_backend_network

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - reactions_backend_network

networks:
  reactions_backend_network:

volumes:
  pgdata_dev: